# Use the official Node.js 20 image as a base
FROM node:20-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY ./api/* ./

# Install the dependencies
RUN npm install

# Expose the port that the application will run on
EXPOSE 8087

# Start the application
CMD ["node", "SrvOndeGastei.js"]